### ISSUE TITLE
Loading saved settings gives error

### ISSUE THREAD

**Issue by Fietsenwiel** [SignalK/instrumentpanel#175]
When I try to load the earlier saved settings I get an error:  

192.168.0.x:3000 meldt het volgende
an error occured in load of settings

It happens with all my devices (laptop, Smartphone, Tablet) and with different browsers (Edge, Chrome, InternetExplorer).

**Comment by cmotelet** [comment]
The settings are saved on the server in a single file when you save for "save for global settings" located at : signalk home .signalk/applicationData/global/instrumentpanel/1.0.0.json or for "save for this user XXX" located at : signalk home .signalk/applicationData/users/XXX/instrumentpanel/1.0.0.json.
One of these files may be corrupted.
Can you send me the file to check it ?

**Comment by Fietsenwiel** [comment]
Hi, thanks for your reply.

The 1.0.0.json look like this:

[1.0.0.json.txt](https://github.com/SignalK/instrumentpanel/files/5898282/1.0.0.json.txt)

My goal is to save the layout and restore it on a onther device. Now I know I also can save only the layout, that works well.

But another problem is tha I want to change the colors of the instruments (in the defaults.json file). That wos not an problem.
But when I change two devices it deosn't work anymore, see my default.json file:

[defaults.json.txt](https://github.com/SignalK/instrumentpanel/files/5898286/defaults.json.txt)

Whar it wrong with this defaults.json file?

Thanks in advance

**Comment by cmotelet** [comment]
I restored your `1.0.0.json` and there are no errors in it.

I corrected your default.json. 
When you declare a path, it must be an object {} and not an array []  ( not `"energy": [`  ).
And you added an extra {} after energy.
[defaults.json.fixed.txt](https://github.com/SignalK/instrumentpanel/files/5898551/defaults.json.fixed.txt)
![2021-01-30 19_25_26-SignalK Instrumentpanel](https://user-images.githubusercontent.com/31212553/106365594-e5387b80-6336-11eb-8c72-d6457c72c488.png)

If you still can't reload your backup, you'll have to activate the debugger in chrome to get a little more information about the error.

**Comment by Fietsenwiel** [comment]
Thank, you realy did help me. The instruments looks good now!
An for me is saving the layout good enough to load it on an other device.

Again, thanks!

**Comment by cmotelet** [comment]
Is backup/restore working for you now or is there still an error?

**Comment by cmotelet** [comment]
I misinterpreted your issue, I thought there was an error in the restore from the server. I just noticed that you were talking about restoring from a file. Indeed, yes there is an error.
I will correct it.
Thank you

**Comment by cmotelet** [comment]
closed via #178 fixed in release in v0.17.2

**Comment by Fietsenwiel** [comment]
Hi,
Yes, i had also an issue with the restore of the local file (save all settings). And I still have that problem, j(ust tried).
For me this is not important anymore, saving "page layout" is for me fine now.

Thanks!

**Comment by Fietsenwiel** [comment]
Oh, I think had had to update, I didn't. Try it later...

**Comment by Fietsenwiel** [comment]
ok, tried ater updating and restarting but I still can't restore the "save all settings" locae file.

**Comment by cmotelet** [comment]
The new release not yet publish on NPM only on Github.
we are currently working with Teppo to set up an automatic publishing process to NPM.
A little more patience ;-)

**Comment by cmotelet** [comment]
The release 0.17.3 is now published on NPM with the fix.
You can update from the Signal K GUI
